// <auto-generated />
using System;
using FoaieDeParcurs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoaieDeParcurs.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823192233_RemoveGoogleMapsApiKey")]
    partial class RemoveGoogleMapsApiKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FoaieDeParcurs.Core.Entities.FillUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LitersFilled")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OdometerReading")
                        .HasColumnType("REAL");

                    b.Property<string>("ReceiptPhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StationLatitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("StationLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("StationLongitude")
                        .HasColumnType("REAL");

                    b.Property<string>("StationName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FillUps");
                });

            modelBuilder.Entity("FoaieDeParcurs.Core.Entities.GpsRawPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Accuracy")
                        .HasColumnType("REAL");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Speed")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GpsRawPoints");
                });

            modelBuilder.Entity("FoaieDeParcurs.Core.Entities.KnownLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RadiusMeters")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("KnownLocations");
                });

            modelBuilder.Entity("FoaieDeParcurs.Core.Entities.RouteSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<int?>("EndFillUpId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("EndLocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolylineEncoded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartFillUpId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("REAL");

                    b.Property<string>("StartLocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RouteSegments");
                });

            modelBuilder.Entity("FoaieDeParcurs.Core.Entities.VehicleProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cui")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailBodyTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailRecipient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSubjectTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelConsumptionNormPer100Km")
                        .HasColumnType("REAL");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportingCadence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleMakeModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehiclePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VehicleProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
